from enum import Enum


class Resource(Enum):
    FUEL = 1,
    MANPOWER = 2,
    MUNITIONS = 3


DEFAULT_TIME_SCALE = 1
time_scale_global = None

MEDIUM_COST_FUEL = 200
HEAVY_COST_FUEL = 600

MEDIUM_RESPAWN_TIME_M = 5
LIGHT_RESPAWN_TIME_M = 5
RECON_RESPAWN_TIME_M = 5

ACCUMULATE_INTERVAL_S = 60

BUTTON_HEIGHT = 10
BUTTON_WIDTH = 25
PROGRESS_WIDTH = 100

GAME_TIME_S = 90 * 60.0

#manpower cooldowns
COOLDOWN_AIRHEAD_M = 10
COOLDOWN_ENCOURAGE_M = 10
COOLDOWN_REINFORCE_M = 5

#munitions cooldowns
COOLDOWN_SUPPLY_DROP_M = 2
COOLDOWN_RECON_PLANE_M = 5
COOLDOWN_STRAFING_RUN_M = 4
COOLDOWN_BOMBING_RUN_M = 10
COOLDOWN_ROCKET_STRIKE_M = 5
COOLDOWN_PRECISION_STRIKE_M = 20

#vehicle cooldowns
COOLDOWN_HALFTRACK_M = 5
COOLDOWN_LIGHT_TANK_M = 1.5
COOLDOWN_MEDIUM_TANK_M = 4 + 1/6
COOLDOWN_HEAVY_TANK_M = 5
COOLDOWN_RECON_TANK_M = 1.5
COOLDOWN_JEEP_M = 5
COOLDOWN_TRUCK_M = 2

#manpower costs
COST_AIRHEAD_MAN = 400
COST_REINFORCE_MAN = 200
COST_ENCOURAGE_MAN = 400

#munitions costs
COST_SUPPLY_DROP_MUN = 50
COST_RECON_PLANE_MUN = 150
COST_STRAFING_RUN_MUN = 150
COST_BOMBING_RUN_MUN = 300
COST_ROCKET_STRIKE_MUN = 300
COST_PRECISION_STRIKE_MUN = 250

#vehicle costs
COST_HALFTRACK_FUEL = 300
COST_LIGHT_TANK_FUEL = 150
COST_MEDIUM_TANK_FUEL = 200
COST_HEAVY_TANK_FUEL = 600
COST_RECON_TANK_FUEL = 100
COST_JEEP_FUEL = 80
COST_TRUCK_FUEL = 100